name: homemon-backend-dev

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ../src:/app/src
      - ../logs:/app/logs
    environment:
      TZ: "Europe/Berlin"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: