name: Run test and generate coverage report

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on:  ubuntu-latest
    
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up docker buildx
              uses: docker/setup-buildx-action@v3

            - name: Run tests with docker and generate coverage report
              run: |
                  docker build --no-cache -f ./docker/Dockerfile.jest -t homemon-backend:jest ./
                  docker run --rm -v ${{ github.workspace }}/src:/app/src -v ${{ github.workspace }}/coverage:/app/coverage homemon-backend:jest
            
            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                    name: coverage-report
                    path: coverage/cobertura-coverage.xml
                
            - name: Update code coverage badge
              run: |
                curl -X POST https://badges.maxlehmann.dev/project/maxlehmann01@homemon-backend/code-coverage \
                -H "Authorization: Bearer ${{ secrets.BADGES_TOKEN }}" \
                -H "Content-Type: application/xml" \
                --data-binary @coverage/cobertura-coverage.xml

    